### ISSUE TITLE
[Feature Request] Hide Xbox Game Pass Launcher Window.

### ISSUE THREAD

**Issue by MrNaughtZero** [jazir555/GamesDows#12]
Hey,

Great work so far on this script, it runs perfectly and makes the Legion Go run like a console without the interference on Windows. The only minor downside to this, is when adding Games from Xbox Game Pass to Steam via UWPHook and launching a game, such as Call of Duty, it shows the Xbox Game Pass launcher window, and also the task bar now becomes visible. This will be visible for up to 60 seconds - depending on the game.

I think it would be a great feature if we can hide this window, and only open it when the game is loaded. Usually, if the launcher window has the maximize window button, this would mean the game has fully loaded - so maybe perform a check to see if this visible, and if not, hide this window?

Let me know your thoughts if this can be achieved, or if there is an alternative?

**Comment by jazir555** [comment]
> Hey,
> 
> Great work so far on this script, it runs perfectly and makes the Legion Go run like a console without the interference on Windows. The only minor downside to this, is when adding Games from Xbox Game Pass to Steam via UWPHook and launching a game, such as Call of Duty, it shows the Xbox Game Pass launcher window, and also the task bar now becomes visible. This will be visible for up to 60 seconds - depending on the game.
> 
> I think it would be a great feature if we can hide this window, and only open it when the game is loaded. Usually, if the launcher window has the maximize window button, this would mean the game has fully loaded - so maybe perform a check to see if this visible, and if not, hide this window?
> 
> Let me know your thoughts if this can be achieved, or if there is an alternative?

You'd need to try to find another project which handles this, probably UWPHook themselves since this is not a related issue to this script unfortunately. 

The taskbar appearing for 60 seconds is a similar one I'm still trying to tackle with this project, I still need to find a way to suppress it. Whenever I figure out a solution for that I'll let you know, but no ETA on that since I've been trying to fix other issues.

Currently working on refining my Wordpress plugin for local hosting assets, once I finish that I'll swing back to this. But for now I recommend checking in with the UWPHook devs to see how to suppress the Game Pass Launcher Window.

**Comment by jazir555** [comment]
I'm closing this since this is out of the scope of GamesDows
