### ISSUE TITLE
Playnite loosed sound and stops responding to controller when windows boots after the delay.

### ISSUE THREAD

**Issue by Staghelm715** [jazir555/GamesDows#15]
I'm pretty sure that means it goes out of the foreground, because when I click the guide button to refocus playnite it goes back to working. It's nothing serious, but just an annoyance; especially when I use my switch controller that doesn't have a guide button bind.

**Comment by jazir555** [comment]
Hi @Staghelm715! Thank for you the report, noted! This has the same root cause as one of the other identified issues in the readme, which is that explorer steals the Window focus when it launches (the issue I'm referring to is the taskbar momentarily appearing over Steam). 

I'm still trying to figure out a solution for preventing explorer from stealing focus when it launches in the background.
