### ISSUE TITLE
How could I add another exe to run along side steam bpm before windows?

### ISSUE THREAD

**Issue by Staghelm715** [jazir555/GamesDows#9]
I want to run CSSLoader-standalone-headless.exe with steam. This changes the steam bpm ui, but has to be running to work. With this enabled, I have to wait for windows delay, then for css loader to start. I have no knowledge in doing this, so any help would be appreciated!

**Comment by jazir555** [comment]
You could modify my V2 version on the testing branch to incorporate commands into the VB Script which is initially set as the shell to launch it alongside Steam in the launch order you'd prefer:

https://github.com/jazir555/GamesDows/blob/jazir555-testing/Enable%20GamesDows%20v2.bat

You can get ChatGPT/Claude to edit it in, it's going to take a bit of trial and error to get it to work, but since you're only going to be modifying the section between lines 26 and 41 it wouldn't take too much effort or time.

**Comment by Staghelm715** [comment]
> You could modify my V2 version on the testing branch to incorporate commands into the VBScript which is initially set as the shell to launch it alongside Steam in the launch order you'd prefer:
> 
> 
> 
> https://github.com/jazir555/GamesDows/blob/jazir555-testing/Enable%20GamesDows%20v2.bat
> 
> 
> 
> You can get ChatGPT/Claude to edit it in, it's going to take a bit of trial and error to get it to work, but since you're only going to be modifying the section between lines 26 and 41 it wouldn't take too much effort or time. You can launch it with the same method as I'm launching Steam, with a powershell command.

I couldn't figure it out, unfortunately. I tried chat gpt and I tried to do by myself, but I pretty much have no idea what I'm doing. Btw, the v2 test is working fine for me.

**Comment by jazir555** [comment]
So explorer is now launching in the background correctly?

**Comment by Staghelm715** [comment]
Well, it did. It just stopped working all of the sudden and now file explorer opens by itself every time I turn on my pc. 

I tried disabling it and I get this ![image](https://github.com/user-attachments/assets/958a57c2-5a8a-4b59-8657-e93d2d44d310)

It is doing the same thing as I showed in the video from the last v2.

**Comment by jazir555** [comment]
What video? There's no video in this thread.

**Comment by Staghelm715** [comment]
I opened an issue yesterday about the first v2, that had the video; It was closed. Sorry, I had to restore my computer to a couple days ago; the image I sent wouldn't go away and file explorer kept showing up.

**Comment by jazir555** [comment]
> I opened an issue yesterday about the first v2 that had the video; it was closed. Sorry, I had to restore my computer to a couple of days ago because the image I sent wouldn't go away, and File Explorer kept showing up.

Ah thanks, didn't realize this was a second issue. I'll give it a look either later tonight or tomorrow and I'll get back to you.

**Comment by jazir555** [comment]
> Okay. Sounds good!

I'm still working on a functional V2 variant, hopefully will have something functional relatively soon. I've been busy with other stuff, but I promise, I will get to it eventually!

**Comment by jazir555** [comment]
> I want to run CSSLoader-standalone-headless.exe with steam. This changes the steam bpm ui, but has to be running to work. With this enabled, I have to wait for windows delay, then for css loader to start. I have no knowledge in doing this, so any help would be appreciated!

As to this question, you could add a copy of the command to start explorer.exe in the delayed explorer start and modify it to launch the exe you mentioned by changing the path in the second command. I could try to create a secondary version for you on testing to see if I can get this working, but since I don't use CSS loader it may take a few iterations.
